version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to docker
          command: |
            docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
      - run:
          name: Pulling docker image
          command: |
            docker pull decidim/decidim-monitor || true
      - run:
          name: Build image
          command: |
            docker build -t registry.heroku.com/decidim-monitor/web --cache-from decidim/decidim-monitor:latest .
      - run:
          name: Push deployment image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push registry.heroku.com/decidim-monitor/web
            fi
