version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Heroku CLI
          command: |
            apk add --update nodejs nodejs-npm
            npm install --global heroku
      - run:
          name: Pulling docker image
          command: |
            docker pull decidim/decidim-monitor || true
      - run:
          name: Build image
          command: |
            docker build -t registry.heroku.com/decidim-monitor/web -t decidim/decidim-monitor:latest --cache-from decidim/decidim-monitor .
      - run:
          name: Run tests
          command: |
            docker build -t decidim-monitor:ci -f Dockerfile.ci --build-arg FROM=decidim/decidim-monitor:latest .
            docker run -it decidim-monitor:ci
      - run:
          name: Push deployment image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              heroku container:release web
            fi
      - run:
          name: Push docker hub image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login --username=$DOCKER_USER --password=$DOCKER_PASS
              docker push decidim/decidim-monitor:latest
            fi