version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to docker
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
            fi
      - run:
          name: Pulling docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker pull registry.heroku.com/decidim-monitor/web || true
            fi
      - run:
          name: Build image
          command: docker build -t registry.heroku.com/decidim-monitor/web .
      - run:
          name: Push image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push registry.heroku.com/decidim-monitor/web
            fi
deployment:
  production:
    branch: production
    commands:
      - ./deploy_prod.sh
