version: '3.3'
services:
  app:
    build:
      context: .
      args:
        - MIX_ENV=dev
    volumes:
      - .:/code:delegated
      - node_modules:/code/frontend/node_modules:delegated
    ports:
      - 4000:4000
    entrypoint: mix
    command: phx.server
    environment: 
      MIX_ENV: dev
volumes:
  node_modules:
