version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      cache_from:
        - decidim/decidim-monitor-dev
    volumes:
      - .:/code
      - node_modules:/code/frontend/node_modules
      - build:/code/_build
      - dependencies:/code/deps
    ports:
      - 4000:4000
    command: phx.server
volumes:
  node_modules:
  build:
  dependencies:
