version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code:delegated
      - node_modules:/code/frontend/node_modules:delegated
      - build:/code/_build:delegated
      - dependencies:/code/deps:delegated
    ports:
      - 4000:4000
    command: mix phx.server
volumes:
  node_modules:
  build:
  dependencies:
