version: '3'
services:
  app:
    build:
      context: .
      image: decidim/decidim-monitor-dev
      args:
        mix_env: dev
    volumes:
      - .:/code
      - node_modules:/code/frontend/node_modules
      - build:/code/_build
      - dependencies:/code/deps
    ports:
      - 4000:4000
    command: phx.server
volumes:
  node_modules:
  build:
  dependencies:
